resource_group_name   = "myResourceGroup"
#storage_account_name  = "${var.storageaccount}"
#container_name        = "${var.containername}"
storage_account_name  = "task2straccount"
container_name        = "cont2tasker"
key                   = "qa/terraform.tfstate"
